---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_facts:
      cloud: "{{osp_cloud}}"
      region_name: "{{osp_region}}"
    register: result
  - name: Delete instances
    os_server:
      cloud: "{{osp_cloud}}"
      name: "{{ item.name }}"
      state: absent
    loop: "{{result.ansible_facts.openstack_servers}}" 
