---
# tasks file for osp.servers
- name: Create osp server instance
  os_server:
    cloud: openstack
    name: "{{ item.0.name }}"
    image: "{{ item.0.image }}"
    key_name: "{{ item.0.key_name }}"
    flavor: "{{ item.0.flavor }}"
    security_groups: "{{ item.0.security_group }}"
    nics:
      - net-name: int_network
    meta: "{{ item.1 }}"
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  with_subelements:
    - "{{ osp_servers }}"
    - meta
  tags:
    - test.servers
    
- name: Check the all OSP instance are running up
  os_server_action:
    action: start
    cloud: openstack
    server: "{{ item.0.name }}"
    timeout: 600
  with_subelements:
    - "{{ osp_servers }}"
    - meta
  tags:
    - test.servers

- name: Add floating IP to instances
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item.value.name }}"
    network: ext_network
    wait: true
    timeout: 200
  with_dict: 
    - "{{ osp_servers }}"
  tags:
    - test.servers
  
- name: OpenStack servers
  os_server_facts:
    cloud: openstack
  register: result
  tags:
    - test.servers

- name: Wait for server to be available
  wait_for:
    host: "{{ item.public_v4 }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600
  delegate_to: "{{ inventory_hostname }}"
  with_items: 
    - "{{ result.ansible_facts.openstack_servers }}"
  tags:
    - test.servers
